"""KS-0017: the template-validate receipt must reflect what the template ships.

`forge template validate` rendered its throwaway smoke project with
with_docker=True and with_jenkins=True unconditionally, so the receipt reported
both enabled even for a template that ships neither file. The receipt dies with
the temporary directory, so nothing downstream was corrupted -- but a receipt
that misreports what it just built is not a receipt.
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

from forge.cli import create_project, resolve_template_dir, template_ships_optional

REPO = Path(__file__).resolve().parent.parent


def _receipt(target: Path) -> dict:
    return json.loads((target / ".forge" / "project.json").read_text(encoding="utf-8"))


def test_detects_a_template_that_ships_neither_file():
    assert template_ships_optional(resolve_template_dir("docs-control-plane")) == (False, False)


def test_detects_a_template_that_ships_both():
    assert template_ships_optional(resolve_template_dir("python-cli")) == (True, True)


def test_detection_is_per_file_not_all_or_nothing(tmp_path):
    t = tmp_path / "half"
    t.mkdir()
    (t / "template.json").write_text("{}", encoding="utf-8")
    (t / "Dockerfile.tmpl").write_text("FROM scratch\n", encoding="utf-8")
    assert template_ships_optional(t) == (True, False)


def test_a_directory_is_not_mistaken_for_a_shipped_file(tmp_path):
    t = tmp_path / "dirnamed"
    (t / "Dockerfile.tmpl").mkdir(parents=True)
    assert template_ships_optional(t) == (False, False)


def test_receipt_matches_the_generated_tree_for_every_template():
    """The reproduction, generalised. Before the fix this failed for
    docs-control-plane: the receipt claimed both were enabled and neither file
    existed on disk."""
    for tpl_dir in sorted((REPO / "templates").iterdir()):
        if not tpl_dir.is_dir():
            continue
        tpl = tpl_dir.name
        docker, jenkins = template_ships_optional(resolve_template_dir(tpl))
        with tempfile.TemporaryDirectory() as td:
            target = create_project(
                name=f"{tpl}-validate-smoke",
                template=tpl,
                output_dir=td,
                description="Generated by Forge template validation.",
                with_docker=docker,
                with_jenkins=jenkins,
            )
            r = _receipt(Path(target))
            assert r["docker_enabled"] == (Path(target) / "Dockerfile").exists(), tpl
            assert r["jenkins_enabled"] == (Path(target) / "Jenkinsfile").exists(), tpl


def test_resolver_rejects_an_unknown_template():
    import pytest
    with pytest.raises(FileNotFoundError):
        resolve_template_dir("no-such-template-ks0017")
