from forge.cli import build_parser, create_project


def test_parser_exists():
    parser = build_parser()
    assert parser.prog == "forge"


def test_create_project(tmp_path):
    target = create_project(
        name="hello-worker",
        template="python-worker",
        output_dir=str(tmp_path),
    )

    assert target.exists()
    assert (target / "README.md").exists()
    assert "Generated by Forge" in (target / "README.md").read_text()
