import argparse
from pathlib import Path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="forge",
        description="Local project scaffolding CLI for Friday.",
    )

    subparsers = parser.add_subparsers(dest="command")

    new_parser = subparsers.add_parser(
        "new",
        help="Create a new project from a template.",
    )
    new_parser.add_argument("name", help="Project name to create.")
    new_parser.add_argument(
        "--template",
        default="python-worker",
        help="Template name to use.",
    )
    new_parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory where the project should be created.",
    )

    return parser


def create_project(name: str, template: str, output_dir: str) -> Path:
    target = Path(output_dir).expanduser().resolve() / name

    if target.exists():
        raise FileExistsError(f"Target already exists: {target}")

    target.mkdir(parents=True)

    readme = target / "README.md"
    readme.write_text(
        f"# {name}\n\n"
        f"Generated by Forge using template `{template}`.\n",
        encoding="utf-8",
    )

    return target


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "new":
        target = create_project(args.name, args.template, args.output_dir)
        print(f"Created project: {target}")
        return

    parser.print_help()


if __name__ == "__main__":
    main()
