"""KS-0006: bounded Forge -> Coder/Terraform target conversion.

Converts the ONE representative Forge template profile this repository's
target contract covers -- a frontend-classified `node-<N>` template, matching
`templates/node-dashboard` -- into a StarkGrid
coder-terraform-target-contract-v1-shaped `main.tf` + `FORGE_SOURCE.md`.
Deliberately bounded, not a general Forge -> Terraform framework: any input
outside that one profile is refused explicitly by `check_source_supported`,
never guessed at. Building a generic multi-target translator is explicitly
out of scope for this item.

Target contract owner: StarkGrid.
  docs/contracts/coder-terraform-target-contract-v1.md
  docs/contracts/forge-node-dashboard-to-starkgrid-frontend-mapping-v1.md
  (StarkGrid v3.0.0-dev 575130340de3241cac2eeabeaa19192aa0ca302a at authoring
  time -- a VERSIONED CONTRACT DEPENDENCY. This module has no runtime
  dependency on a live StarkGrid checkout; conformance is proven by this
  repository's own test suite against pinned reference fixtures under
  tests/fixtures/coder_target/ -- see STARKGRID_CONTRACT_PIN.md there.)

Node 20/22 discrepancy, resolved exactly as the mapping document's own worked
example already does: the mapping records that the live starkgrid-frontend
workspace image is Node 22 while node-dashboard declares node-20, and states
a future converter "would need to resolve this discrepancy explicitly (pin
the workspace image to Node 20...)". This module derives the devcontainer
image tag from the Forge template's OWN declared `runtime` field -- so the
generated image tracks whatever Forge declares (node-20 today) rather than
silently inheriting starkgrid-frontend's unrelated, already-live Node 22
default. That default is never read by this module at all.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from forge.renderer import render_text

FORGE_REPOSITORY = "qmcclellan/forge"

REQUIRED_LANGUAGE = "node"
REQUIRED_TAG = "frontend"
RUNTIME_PATTERN = re.compile(r"^node-(\d+)$")
DEVCONTAINER_IMAGE_TEMPLATE = "mcr.microsoft.com/devcontainers/javascript-node:1-{version}-bullseye"

# {{ key }} placeholders, matching forge.renderer.render_text's own
# convention exactly -- reused rather than a second templating mechanism.
# HCL's ${...} interpolation syntax does not collide with it (no `{{ }}`
# anywhere Terraform itself would emit), so it passes through untouched.
MAIN_TF_TEMPLATE = """terraform {
  required_providers {
    coder  = { source = "coder/coder" }
    docker = { source = "kreuzwerker/docker" }
  }
}

provider "docker" {}

data "coder_workspace" "me" {}
data "coder_workspace_owner" "me" {}

variable "workspace_image" {
  default     = "{{ workspace_image }}"
  description = "Devcontainer image for the provisioned workspace, derived from the Forge source template's declared runtime ({{ runtime }}) -- see docs/contracts/forge-node-dashboard-to-starkgrid-frontend-mapping-v1.md's 'Honest discrepancy' section for why the hand-imported starkgrid-frontend target does not do this."
  type        = string
}

resource "coder_agent" "main" {
  os   = "linux"
  arch = "amd64"

  startup_script = <<-EOT
    set -e
    npm install -g npm@latest || true
    node -v || true
    npm -v || true
  EOT
}

resource "docker_volume" "home_volume" {
  name = "coder-${data.coder_workspace_owner.me.name}-${lower(data.coder_workspace.me.name)}-home"
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = var.workspace_image

  name     = "coder-${data.coder_workspace_owner.me.name}-${lower(data.coder_workspace.me.name)}"
  hostname = data.coder_workspace.me.name

  entrypoint = [
    "sh",
    "-c",
    coder_agent.main.init_script
  ]

  env = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}",
  ]

  volumes {
    container_path = "/home/node"
    volume_name    = docker_volume.home_volume.name
    read_only      = false
  }
}

module "code-server" {
  source  = "registry.coder.com/coder/code-server/coder"
  version = "1.4.4"

  agent_id = coder_agent.main.id
}
"""

FORGE_SOURCE_MD_TEMPLATE = """# FORGE SOURCE -- {{ template_name }}

Required fields for coder-terraform-target-contract-v1.md section 5
(provenance), Forge-derived case.

- Forge template: `templates/{{ template_name }}`
- Forge repository: `{{ forge_repository }}`
- Forge SHA: `{{ forge_sha }}`
- Generated: {{ generated_at }}
- Generator: `forge template convert-coder` ({{ forge_repository }}, KS-0006)

## Statements

- This target was generated by Forge's bounded Forge-to-Coder conversion. It
  is not published to Coder and provisions nothing by existing.
- Structural conformance to coder-terraform-target-contract-v1.md is proven
  by this repository's own test suite, not asserted here.
"""


class UnsupportedForgeSource(ValueError):
    """Raised when a Forge template does not match the one profile this
    converter is bounded to. Never guessed past -- an unsupported input must
    fail loudly rather than produce plausible-looking output (KS-0006 Phase E)."""


def _load_manifest(template_dir: Path) -> dict:
    manifest_path = template_dir / "template.json"
    if not manifest_path.is_file():
        raise UnsupportedForgeSource(f"missing template.json in {template_dir}")
    try:
        return json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise UnsupportedForgeSource(f"malformed template.json in {template_dir}: {exc}") from exc


def _devcontainer_image_for_runtime(runtime) -> str:
    if not isinstance(runtime, str):
        raise UnsupportedForgeSource(f"template.json 'runtime' must be a string, got {runtime!r}")
    m = RUNTIME_PATTERN.match(runtime)
    if not m:
        raise UnsupportedForgeSource(
            f"unsupported runtime {runtime!r} -- this converter only maps node-<N> runtimes "
            "(the node-dashboard-shaped profile); it never fabricates an image for anything else"
        )
    return DEVCONTAINER_IMAGE_TEMPLATE.format(version=m.group(1))


def check_source_supported(manifest: dict) -> None:
    """Raises UnsupportedForgeSource with a specific, identifiable reason;
    returns None when the manifest is within the one bounded profile this
    converter accepts: language "node" AND "frontend" in tags AND a runtime
    shaped "node-<N>". See the module docstring for why this is bounded
    rather than generalized to arbitrary Forge templates.
    """
    for field in ("name", "language", "runtime"):
        if not manifest.get(field):
            raise UnsupportedForgeSource(f"template.json missing required field: {field}")

    if manifest["language"] != REQUIRED_LANGUAGE:
        raise UnsupportedForgeSource(
            f"unsupported language {manifest['language']!r} -- this converter only supports "
            f"{REQUIRED_LANGUAGE!r}-language, frontend-tagged templates (the node-dashboard profile)"
        )

    tags = manifest.get("tags")
    if not isinstance(tags, list) or REQUIRED_TAG not in tags:
        raise UnsupportedForgeSource(
            f"unsupported classification: tags {tags!r} do not include {REQUIRED_TAG!r} -- "
            "this converter only supports frontend-classified templates"
        )

    _devcontainer_image_for_runtime(manifest["runtime"])  # raises on an unsupported runtime shape


def convert_to_coder_target(template_dir: Path, forge_sha: str, generated_at: str) -> dict:
    """Converts one Forge template directory into StarkGrid
    coder-terraform-target-contract-v1-shaped output.

    Returns {"main_tf": str, "forge_source_md": str, "manifest": dict}.
    Raises UnsupportedForgeSource -- never returns a partial or best-guess
    result -- for anything outside the one bounded profile this module
    supports (Phase E). `forge_sha` and `generated_at` are CALLER-SUPPLIED,
    never inferred from local git state or the wall clock, so identical
    inputs always produce byte-identical output (Phase G) and no
    host-dependent value leaks into the generated artifact.
    """
    if not forge_sha or not isinstance(forge_sha, str):
        raise UnsupportedForgeSource("forge_sha is required and must be a non-empty string")
    if not generated_at or not isinstance(generated_at, str):
        raise UnsupportedForgeSource("generated_at is required and must be a non-empty string")

    manifest = _load_manifest(template_dir)
    check_source_supported(manifest)

    image = _devcontainer_image_for_runtime(manifest["runtime"])
    main_tf = render_text(MAIN_TF_TEMPLATE, {"workspace_image": image, "runtime": manifest["runtime"]})
    forge_source_md = render_text(
        FORGE_SOURCE_MD_TEMPLATE,
        {
            "template_name": manifest["name"],
            "forge_repository": FORGE_REPOSITORY,
            "forge_sha": forge_sha,
            "generated_at": generated_at,
        },
    )
    return {"main_tf": main_tf, "forge_source_md": forge_source_md, "manifest": manifest}


def write_coder_target(template_dir: Path, output_dir: Path, forge_sha: str, generated_at: str) -> dict:
    """Converts, then writes main.tf and FORGE_SOURCE.md to output_dir.

    Structural conformance is the CALLER's job (run StarkGrid's own
    validate-target-contract.sh against output_dir, or the pinned reference
    copy under tests/fixtures/coder_target/ for this repository's own tests)
    -- this function converts and writes; it never invokes any StarkGrid
    tooling itself, keeping runtime conversion decoupled from a live
    StarkGrid checkout (KS-0006 Phase N).
    """
    result = convert_to_coder_target(template_dir, forge_sha, generated_at)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "main.tf").write_text(result["main_tf"], encoding="utf-8")
    (output_dir / "FORGE_SOURCE.md").write_text(result["forge_source_md"], encoding="utf-8")
    return result
